# Generated by Django 4.1.5 on 2023-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_ticket_time_created_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
